console.log("Rodando o sistema de gerenciamento de jogos")
console.log("aplicação está se conectando ao banco de dados")
console.log("testando git")
console.log("testando git 02")
console.log("testando nova alteração")
console.log("nova alteração último arquivo app")